import type { Customer } from "@/types/customer";
import type { Ticket } from "@/types/ticket";
import type { UserProfile } from "@/types/user";

// Minimal Timestamp-compatible shim for mock data
function ts(date: Date) {
  return {
    toDate: () => date,
    seconds: Math.floor(date.getTime() / 1000),
    nanoseconds: 0,
    toMillis: () => date.getTime(),
  } as ReturnType<typeof import("firebase/firestore").Timestamp.fromDate>;
}

const now = new Date();
const yesterday = new Date(now.getTime() - 86400000);

// Returns a Date for the given day of the current week (0=Mon … 6=Sun)
// at the specified hour and minute
function weekDay(dayIndex: number, hour: number, minute = 0): Date {
  const d = new Date(now);
  const currentDay = d.getDay(); // 0=Sun … 6=Sat
  const diffToMonday = currentDay === 0 ? -6 : 1 - currentDay;
  d.setDate(d.getDate() + diffToMonday + dayIndex);
  d.setHours(hour, minute, 0, 0);
  return d;
}

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "mock-customer-1",
    companyName: "Acme Corp",
    contactName: "John Smith",
    email: "john@acmecorp.com",
    phone: "(555) 100-2000",
    address: { street: "123 Main St", city: "Springfield", state: "IL", zip: "62701" },
    notes: "Long-term client, prefers morning appointments.",
    isActive: true,
    createdBy: "mock-admin-uid",
    createdAt: ts(yesterday),
    updatedAt: ts(yesterday),
  },
  {
    id: "mock-customer-2",
    companyName: "Beta Solutions",
    contactName: "Sarah Johnson",
    email: "sarah@betasolutions.com",
    phone: "(555) 200-3000",
    address: { street: "456 Oak Ave", city: "Shelbyville", state: "IL", zip: "62565" },
    isActive: true,
    createdBy: "mock-admin-uid",
    createdAt: ts(yesterday),
    updatedAt: ts(yesterday),
  },
  {
    id: "mock-customer-3",
    companyName: "Gamma Industries",
    contactName: "Mike Davis",
    email: "mike@gammaindustries.com",
    phone: "(555) 300-4000",
    address: { street: "789 Pine Rd", city: "Capital City", state: "IL", zip: "62702" },
    notes: "New client. HVAC system installed last year.",
    isActive: true,
    createdBy: "mock-admin-uid",
    createdAt: ts(yesterday),
    updatedAt: ts(yesterday),
  },
];

export const MOCK_TICKETS: Ticket[] = [
  // ── Monday ──────────────────────────────────────────────────────────────
  {
    id: "mock-ticket-1",
    customerId: "mock-customer-1",
    customerName: "Acme Corp",
    description: "Server room AC unit not cooling properly. Temperature rising above threshold.",
    priority: "urgent",
    status: "in_progress",
    assignedTechnicianId: "mock-tech-uid",
    assignedTechnicianName: "Alex Tech",
    scheduledDate: ts(weekDay(0, 8)),
    scheduledTime: "08:00",
    estimatedDuration: 90,
    createdBy: "mock-admin-uid",
    createdAt: ts(yesterday),
    updatedAt: ts(yesterday),
  },
  {
    id: "mock-ticket-2",
    customerId: "mock-customer-2",
    customerName: "Beta Solutions",
    description: "Routine quarterly HVAC filter replacement and system check.",
    priority: "low",
    status: "completed",
    assignedTechnicianId: "mock-tech-uid-2",
    assignedTechnicianName: "Jordan Field",
    scheduledDate: ts(weekDay(0, 14)),
    scheduledTime: "14:00",
    estimatedDuration: 60,
    createdBy: "mock-admin-uid",
    createdAt: ts(yesterday),
    updatedAt: ts(yesterday),
  },
  // ── Tuesday ──────────────────────────────────────────────────────────────
  {
    id: "mock-ticket-3",
    customerId: "mock-customer-3",
    customerName: "Gamma Industries",
    description: "Electrical panel tripping breakers on the production floor. Safety concern.",
    priority: "urgent",
    status: "assigned",
    assignedTechnicianId: "mock-tech-uid-3",
    assignedTechnicianName: "Sam Rivera",
    scheduledDate: ts(weekDay(1, 7, 30)),
    scheduledTime: "07:30",
    estimatedDuration: 120,
    createdBy: "mock-admin-uid",
    createdAt: ts(yesterday),
    updatedAt: ts(yesterday),
  },
  {
    id: "mock-ticket-4",
    customerId: "mock-customer-1",
    customerName: "Acme Corp",
    description: "Install new network patch panel in comms room. 48-port Cat6.",
    priority: "medium",
    status: "assigned",
    assignedTechnicianId: "mock-tech-uid",
    assignedTechnicianName: "Alex Tech",
    scheduledDate: ts(weekDay(1, 10)),
    scheduledTime: "10:00",
    estimatedDuration: 180,
    createdBy: "mock-admin-uid",
    createdAt: ts(yesterday),
    updatedAt: ts(yesterday),
  },
  {
    id: "mock-ticket-5",
    customerId: "mock-customer-2",
    customerName: "Beta Solutions",
    description: "Plumbing leak under kitchen sink on 3rd floor. Needs immediate repair.",
    priority: "high",
    status: "unassigned",
    scheduledDate: ts(weekDay(1, 15)),
    scheduledTime: "15:00",
    estimatedDuration: 60,
    createdBy: "mock-admin-uid",
    createdAt: ts(yesterday),
    updatedAt: ts(yesterday),
  },
  // ── Wednesday (today) ────────────────────────────────────────────────────
  {
    id: "mock-ticket-6",
    customerId: "mock-customer-1",
    customerName: "Acme Corp",
    description: "Replace broken thermostat in server room. Temperature alerts active.",
    priority: "urgent",
    status: "in_progress",
    assignedTechnicianId: "mock-tech-uid-2",
    assignedTechnicianName: "Jordan Field",
    scheduledDate: ts(weekDay(2, 8)),
    scheduledTime: "08:00",
    estimatedDuration: 60,
    createdBy: "mock-admin-uid",
    createdAt: ts(yesterday),
    updatedAt: ts(now),
  },
  {
    id: "mock-ticket-7",
    customerId: "mock-customer-3",
    customerName: "Gamma Industries",
    description: "Annual fire suppression system inspection and certification.",
    priority: "medium",
    status: "assigned",
    assignedTechnicianId: "mock-tech-uid",
    assignedTechnicianName: "Alex Tech",
    scheduledDate: ts(weekDay(2, 10, 30)),
    scheduledTime: "10:30",
    estimatedDuration: 90,
    createdBy: "mock-admin-uid",
    createdAt: ts(yesterday),
    updatedAt: ts(yesterday),
  },
  {
    id: "mock-ticket-8",
    customerId: "mock-customer-2",
    customerName: "Beta Solutions",
    description: "HVAC unit making loud noise on the 2nd floor. Inspect and repair.",
    priority: "high",
    status: "unassigned",
    scheduledDate: ts(weekDay(2, 13)),
    scheduledTime: "13:00",
    estimatedDuration: 120,
    createdBy: "mock-admin-uid",
    createdAt: ts(now),
    updatedAt: ts(now),
  },
  {
    id: "mock-ticket-9",
    customerId: "mock-customer-1",
    customerName: "Acme Corp",
    description: "Configure new VoIP phone system for 15 workstations.",
    priority: "medium",
    status: "assigned",
    assignedTechnicianId: "mock-tech-uid-3",
    assignedTechnicianName: "Sam Rivera",
    scheduledDate: ts(weekDay(2, 15, 30)),
    scheduledTime: "15:30",
    estimatedDuration: 120,
    createdBy: "mock-admin-uid",
    createdAt: ts(now),
    updatedAt: ts(now),
  },
  // ── Thursday ──────────────────────────────────────────────────────────────
  {
    id: "mock-ticket-10",
    customerId: "mock-customer-3",
    customerName: "Gamma Industries",
    description: "Water heater not producing hot water. Unit may need replacement.",
    priority: "high",
    status: "assigned",
    assignedTechnicianId: "mock-tech-uid-2",
    assignedTechnicianName: "Jordan Field",
    scheduledDate: ts(weekDay(3, 9)),
    scheduledTime: "09:00",
    estimatedDuration: 90,
    createdBy: "mock-admin-uid",
    createdAt: ts(yesterday),
    updatedAt: ts(yesterday),
  },
  {
    id: "mock-ticket-11",
    customerId: "mock-customer-2",
    customerName: "Beta Solutions",
    description: "Annual electrical panel inspection and certification.",
    priority: "medium",
    status: "unassigned",
    scheduledDate: ts(weekDay(3, 11)),
    scheduledTime: "11:00",
    estimatedDuration: 90,
    createdBy: "mock-admin-uid",
    createdAt: ts(now),
    updatedAt: ts(now),
  },
  {
    id: "mock-ticket-12",
    customerId: "mock-customer-1",
    customerName: "Acme Corp",
    description: "Replace failed UPS battery backup units in server room.",
    priority: "high",
    status: "assigned",
    assignedTechnicianId: "mock-tech-uid-3",
    assignedTechnicianName: "Sam Rivera",
    scheduledDate: ts(weekDay(3, 14, 30)),
    scheduledTime: "14:30",
    estimatedDuration: 60,
    createdBy: "mock-admin-uid",
    createdAt: ts(yesterday),
    updatedAt: ts(yesterday),
  },
  // ── Friday ────────────────────────────────────────────────────────────────
  {
    id: "mock-ticket-13",
    customerId: "mock-customer-2",
    customerName: "Beta Solutions",
    description: "Install security camera system — 8 cameras, NVR setup and configuration.",
    priority: "medium",
    status: "assigned",
    assignedTechnicianId: "mock-tech-uid",
    assignedTechnicianName: "Alex Tech",
    scheduledDate: ts(weekDay(4, 8, 30)),
    scheduledTime: "08:30",
    estimatedDuration: 240,
    createdBy: "mock-admin-uid",
    createdAt: ts(yesterday),
    updatedAt: ts(yesterday),
  },
  {
    id: "mock-ticket-14",
    customerId: "mock-customer-3",
    customerName: "Gamma Industries",
    description: "Clogged floor drain in warehouse causing water backup.",
    priority: "high",
    status: "assigned",
    assignedTechnicianId: "mock-tech-uid-2",
    assignedTechnicianName: "Jordan Field",
    scheduledDate: ts(weekDay(4, 13, 30)),
    scheduledTime: "13:30",
    estimatedDuration: 60,
    createdBy: "mock-admin-uid",
    createdAt: ts(now),
    updatedAt: ts(now),
  },
  {
    id: "mock-ticket-15",
    customerId: "mock-customer-1",
    customerName: "Acme Corp",
    description: "End of week system health check — servers, network, and backup verification.",
    priority: "low",
    status: "unassigned",
    scheduledDate: ts(weekDay(4, 16)),
    scheduledTime: "16:00",
    estimatedDuration: 60,
    createdBy: "mock-admin-uid",
    createdAt: ts(now),
    updatedAt: ts(now),
  },
  // ── Saturday ──────────────────────────────────────────────────────────────
  {
    id: "mock-ticket-16",
    customerId: "mock-customer-2",
    customerName: "Beta Solutions",
    description: "Emergency: office flooding from burst pipe on 2nd floor bathroom.",
    priority: "urgent",
    status: "assigned",
    assignedTechnicianId: "mock-tech-uid-3",
    assignedTechnicianName: "Sam Rivera",
    scheduledDate: ts(weekDay(5, 7)),
    scheduledTime: "07:00",
    estimatedDuration: 180,
    createdBy: "mock-admin-uid",
    createdAt: ts(now),
    updatedAt: ts(now),
  },
  {
    id: "mock-ticket-17",
    customerId: "mock-customer-3",
    customerName: "Gamma Industries",
    description: "Scheduled generator maintenance and load bank testing.",
    priority: "medium",
    status: "unassigned",
    scheduledDate: ts(weekDay(5, 12)),
    scheduledTime: "12:00",
    estimatedDuration: 120,
    createdBy: "mock-admin-uid",
    createdAt: ts(now),
    updatedAt: ts(now),
  },
  // ── Sunday ────────────────────────────────────────────────────────────────
  {
    id: "mock-ticket-18",
    customerId: "mock-customer-1",
    customerName: "Acme Corp",
    description: "After-hours server migration — move 3 servers to new rack, recable.",
    priority: "high",
    status: "assigned",
    assignedTechnicianId: "mock-tech-uid",
    assignedTechnicianName: "Alex Tech",
    scheduledDate: ts(weekDay(6, 8)),
    scheduledTime: "08:00",
    estimatedDuration: 240,
    createdBy: "mock-admin-uid",
    createdAt: ts(now),
    updatedAt: ts(now),
  },
  {
    id: "mock-ticket-19",
    customerId: "mock-customer-2",
    customerName: "Beta Solutions",
    description: "Replace broken window latch on 1st floor — security concern.",
    priority: "low",
    status: "assigned",
    assignedTechnicianId: "mock-tech-uid-2",
    assignedTechnicianName: "Jordan Field",
    scheduledDate: ts(weekDay(6, 11)),
    scheduledTime: "11:00",
    estimatedDuration: 30,
    createdBy: "mock-admin-uid",
    createdAt: ts(now),
    updatedAt: ts(now),
  },
  {
    id: "mock-ticket-20",
    customerId: "mock-customer-3",
    customerName: "Gamma Industries",
    description: "Preventive maintenance on industrial HVAC units — clean coils, check refrigerant.",
    priority: "medium",
    status: "assigned",
    assignedTechnicianId: "mock-tech-uid-3",
    assignedTechnicianName: "Sam Rivera",
    scheduledDate: ts(weekDay(6, 14)),
    scheduledTime: "14:00",
    estimatedDuration: 150,
    createdBy: "mock-admin-uid",
    createdAt: ts(now),
    updatedAt: ts(now),
  },
];

export const MOCK_USERS: UserProfile[] = [
  {
    uid: "mock-admin-uid",
    email: "admin@fieldmanager.dev",
    displayName: "Dev Admin",
    role: "global_admin",
    isActive: true,
    createdAt: ts(yesterday),
    updatedAt: ts(yesterday),
  },
  {
    uid: "mock-tech-uid",
    email: "alex@fieldmanager.dev",
    displayName: "Alex Tech",
    role: "technician",
    isActive: true,
    createdAt: ts(yesterday),
    updatedAt: ts(yesterday),
  },
  {
    uid: "mock-tech-uid-2",
    email: "jordan@fieldmanager.dev",
    displayName: "Jordan Field",
    role: "technician",
    isActive: true,
    createdAt: ts(yesterday),
    updatedAt: ts(yesterday),
  },
  {
    uid: "mock-tech-uid-3",
    email: "sam@fieldmanager.dev",
    displayName: "Sam Rivera",
    role: "technician",
    isActive: true,
    createdAt: ts(yesterday),
    updatedAt: ts(yesterday),
  },
];

export function getMockCustomer(id: string): (Customer & { id: string }) | null {
  return MOCK_CUSTOMERS.find((c) => c.id === id) ?? null;
}

export function getMockTicket(id: string): (Ticket & { id: string }) | null {
  return MOCK_TICKETS.find((t) => t.id === id) ?? null;
}
